name: Export a pdf file
on:
  push:
    branches:
      - main
jobs:
  export-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn
      - name: Format
        run: yarn f
      - name: Build
        run: yarn b
      - name: Export
        run: yarn e
      - name: Set current datetime
        env:
          TZ: "Europe/London"
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CURRENT_DATETIME }}_slidev
          path: ./slides-export.pdf
